spring:
  datasource:
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: auth
    password: 123456
    driver-class-name: org.h2.Driver
    #tomcat:
      #defaultTransactionIsolation: 2 #READ_COMMITTED
      #defaultAutoCommit: true
      #validationQuery: SELECT 1
      #validationQueryTimeout: 30
      #initialSize: 25
      #testOnBorrow: true
      #testWhileIdle: true
    hikari:
      maximumPoolSize: 30
      poolName: my-db-pool
      transactionIsolation: TRANSACTION_READ_COMMITTED
      maxLifetime: 600000
  h2: #http://localhost:8080/h2-console
    console: 
      enabled: true
